# Site settings

title: "The Landscape of Spatial Data Tools"
email: "cyberhelp@sesync.org"
description: "Introduction to the principles, and the open source stack, underlying geospatial analysis."
baseurl: "/osgeo-lesson"

# Jekyll Settings

markdown: kramdown
collections:
  - slides

# Slide Order
slide_sorter:
  - title
  - intro
  - goals
  - types
  - gdal
  - geos
  - gcs
  - pcs
  - distortion
  - conclude
